// Event validation schemas
export {
  createEventSchema,
  updateEventSchema,
  eventQuerySchema,
  createCategorySchema,
  updateCategorySchema,
  type CreateEventInput,
  type UpdateEventInput,
  type EventQueryInput,
  type CreateCategoryInput,
  type UpdateCategoryInput,
} from './event.schemas';

// API validation schemas
export {
  successResponseSchema,
  errorResponseSchema,
  apiResponseSchema,
  paginationSchema,
  paginatedResponseSchema,
  uuidSchema,
  slugSchema as apiSlugSchema,
  timestampSchema,
  imageUploadSchema,
  authTokenSchema,
  userContextSchema,
  createEventRequestSchema,
  updateEventRequestSchema,
  deleteEventRequestSchema,
  getEventRequestSchema,
  listEventsRequestSchema,
  type SuccessResponse,
  type ErrorResponse,
  type ApiResponse,
  type PaginatedResponse,
  type UserContext,
  type AuthToken,
} from './api.schemas';

// Common validation schemas
export {
  emailSchema,
  passwordSchema,
  phoneSchema,
  urlSchema,
  colorHexSchema,
  timezoneSchema,
  currencySchema,
  coordinatesSchema,
  dateStringSchema,
  futureDateSchema,
  pastDateSchema,
  dateRangeSchema,
  titleSchema,
  descriptionSchema,
  excerptSchema,
  slugSchema,
  positiveIntegerSchema,
  nonNegativeIntegerSchema,
  capacitySchema,
  priceAmountSchema,
  imageUrlSchema,
  videoUrlSchema,
  socialMediaUrlSchema,
  solanaAddressSchema,
  ethereumAddressSchema,
  searchQuerySchema,
  sortOrderSchema,
  sortFieldSchema,
  createOptionalSchema,
  createNullableSchema,
  type DateRange,
  type Coordinates,
  type SortOrder,
  type SortField,
} from './common.schemas';

// Re-export Zod for convenience
export { z } from 'zod';